# Generated by Django 3.0.3 on 2020-02-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_use',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
